version: "3.6"

services:
  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASSWORD
    volumes:
      - ./docker/db/multibyte.cnf:/etc/mysql/conf.d/multibyte.cnf
    ports:
      - "13306:3306"
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: development
      DATABASE_URL: "mysql2://root:root@db"
      EDITOR: "vim"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql-data:
  bundle:
  node_modules:
